name: e2e docs test
permissions:
  id-token: write
on:
  pull_request:
    branches:
      - main
jobs:
  run-tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: 'projects/489627518739/locations/global/workloadIdentityPools/github-identities/providers/github-com'
          service_account: 'docs-test-runner@substratus-integration-tests.iam.gserviceaccount.com'
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          install_components: 'google-cloud-cli-gke-gcloud-auth-plugin,kubectl'
          project_id: 'substratus-integration-tests'
      - name: Run tests
        run: |
          sudo apt-get update -y && \
          sudo apt-get install -y --no-install-recommends \
          python3 \
          python3-pip \
          gcc \
          python3-dev && \
          PROJECT_ID=substratus-integration-tests make test
